---
- name: Playbook to install and configure Apache web server
  hosts: all
  become: true
  tasks:
    - name: Install Apache and Php Support for Ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: present
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Ensure Apache is running and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache and Php Support for Fedora
      ansible.builtin.dnf:
        name:
          - httpd
          - php
        state: present
        update_cache: true
      when: ansible_distribution == "Fedora"

    - name: Ensure Httpd is running and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      when: ansible_distribution == "Fedora"
