---
- name: Playbook to install and configure Apache web server
  hosts: all
  become: true
  tasks:
    - name: Install Apache and Php Support for Ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: present
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Ensure Apache is running and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache and Php Support for Fedora
      ansible.builtin.dnf:
        name:
          - httpd
          - php
        state: present
        update_cache: true
      when: ansible_distribution == "Fedora"

    - name: Change HTTPD port to 8180
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen'
        line: 'Listen 8180'
      notify: Restart_httpd
      when: ansible_distribution == "Fedora"

  handlers:
    - name: Restart_httpd
      ansible.builtin.service:
        name: httpd
        state: restarted

    - name: Ensure Httpd is running and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      when: ansible_distribution == "Fedora"
