---
- name: Playbook to remove Apache web server
  hosts: ubuntu_nodes
  become: true
  tasks:
    - name: Remove Apache
      ansible.builtin.apt:
        name: apache2
        state: absent

    - name: Remove php support for Apache
      ansible.builtin.apt:
        name: libapache2-mod-php
        state: absent

    - name: Ensure Apache is running and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
